# Generated by Django 2.1.7 on 2019-03-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190327_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='overall_rating',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
