# Generated by Django 2.1.7 on 2019-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
