# Generated by Django 2.1.7 on 2019-03-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190328_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product_id',
            new_name='product_description',
        ),
    ]
