# Generated by Django 2.1.7 on 2019-03-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190328_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='product_name',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
