# Generated by Django 2.1.7 on 2019-03-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_reviews_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='product',
        ),
        migrations.AddField(
            model_name='reviews',
            name='product_name',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
