# Generated by Django 2.1.7 on 2019-03-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20190328_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='product_id',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
