# Generated by Django 2.1.7 on 2019-03-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_reviews_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='negative_percentage',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='positive_percentage',
        ),
    ]
