# Generated by Django 2.1.7 on 2019-03-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20190330_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
