# Generated by Django 2.1.7 on 2019-03-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='total_score',
            field=models.IntegerField(max_length=100),
        ),
    ]
