# Generated by Django 2.1.7 on 2019-03-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20190330_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['overall_rating']},
        ),
    ]
