# Generated by Django 2.1.7 on 2019-03-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20190330_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['neg_rating']},
        ),
        migrations.AddField(
            model_name='products',
            name='neg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
